apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chatbot-jan17-2 
  janus-idp.io/tekton: chatbot-jan17-2
  backstage.io/kubernetes-id: chatbot-jan17-2
  backstage.io/kubernetes-namespace: chatbot-jan17-2 
  app.kubernetes.io/part-of: chatbot-jan17-2
resources: 
- application-dev.yaml